#!/usr/bin/env python

import sys
import subprocess
import plistlib
import base64
import bz2

from mwa2 import utils

def get_hardware_info():
    '''Uses system profiler to get hardware info for this machine'''
    cmd = ['/usr/sbin/system_profiler', '-xml', 'SPHardwareDataType', 'SPSoftwareDataType',
           'SPNetworkDataType', 'SPInstallHistoryDataType', 'SPDisplaysDataType',
           'SPStorageDataType', 'SPPrintersDataType', 'SPNetworkVolumeDataType',
           'SPThunderboltDataType', 'SPSerialATADataType', 'SPUSBDataType']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, dummy_error) = proc.communicate()
    try:
        plist = plistlib.readPlistFromString(output)
        # system_profiler xml is an array
        newPlist = dict()
        for plistDict in plist:
            newPlist[plistDict['_dataType']] = plistDict['_items']
        return newPlist
    except BaseException:
        return {}

def main():
    """ main """
    RUNTYPE = "unknown"
    if len(sys.argv) == 2:
        RUNTYPE = sys.argv[1]

    REPORTPATH = "/Library/Managed Installs/ManagedInstallReport.plist"
    reportPlist = plistlib.readPlist(REPORTPATH)

    hardwareinfo = get_hardware_info()

    reportPlist["MachineInfo"]["SystemProfile"] = list()
    reportPlist["MachineInfo"]["SystemProfile"] = [hardwareinfo]

    bz2report = bz2.compress(plistlib.writePlistToString(reportPlist))
    base64bz2report = base64.b64encode(bz2report)
    report = base64bz2report.replace(" ", "+")
    
    serialNumber = hardwareinfo["SPHardwareDataType"][0]["serial_number"]
    clientName = utils.get_comnputer_name()
    
    url = "/api/report/"+serialNumber

    data = {"runtype": RUNTYPE, "submission_type": "postflight", "name": clientName, "base64bz2report": report}
    
    resc = utils.send_data(url, data)
    if resc.status_code != 204:
        print("send data error: %s", resc.status_code)
        pass

if __name__ == "__main__":
    main()
